### ISSUE TITLE
Import score precision for tasks

### ISSUE THREAD

**Issue by ahtotruu** [e-i-o/cms#10]
Add an option to the task metadata file to specify the number of decimal places in the score for that task. Currently the precision can be set interactively in the admin interface, but is reset to zero by the import tool every time the task data is updated and re-imported.

Would also be nice if the importer would set the precision of total scores for the contest to be the maximum over the tasks in the contest, though this is less important as the contest parameter does not get reset so easily.

**Comment by prandla** [comment]
now possible with the "score_precision" key in task.yaml. (this came automatically when i rebased estonia_yaml.py on top of the new cms's italy_yaml.py)
