### ISSUE TITLE
Hide execution time from user feedback when solution exceeds time limit

### ISSUE THREAD

**Issue by ahtotruu** [e-i-o/cms#11]
The way the CMS user interface shows execution times is confusing for beginners. When a solutions exceeds the CPU time limit, the test worker kills the solution after a few tens of milliseconds. This execution time gets then shown to the user and it's quite common for the beginners to misread it and go "oh, I'm so close, need to shave off just a fraction of a second for my solution to pass". Better to replace the number with some "N/A" or just even leave it blank in the UI.

![image](https://user-images.githubusercontent.com/720294/196132510-9532952d-4583-4fc9-8972-5968458b87e0.png)

**Comment by prandla** [comment]
implemented in c2c4c52a26727bc156271a57018d716013f2a55d
