### ISSUE TITLE
Enable threading for "batch interactive" task type

### ISSUE THREAD

**Issue by ahtotruu** [e-i-o/cms#12]
The "batch interactive" task type we created to run the solution and the interactor in the same sandbox does not set the sandbox to allow forking. This causes evaluation of those solutions to fail because the interactor can't execute the solution.

This has not been discovered before, because CMS always allows forking for all solutions as soon as at least one "threaded" language (such as Java) is enabled in the contest, and we have had Java enabled for all rounds until now. (The workaround was to enable Java even though no contestant uses it today.)

**Comment by prandla** [comment]
fixed in b44aa0073ad2229dd3a411095bc6667df15284a7

ma mõtlesin et olen nii kaval et seda ise märkasin, siis tuli meelde et siin repos on meil ka issue'd...
