### ISSUE TITLE
submission code view in AWS is annoying

### ISSUE THREAD

**Issue by prandla** [e-i-o/cms#16]
things i'd like to fix:

* the code area doesn't scroll correctly, there is no horizontal scroll at all and the vertical scroll doesn't have a scrollbar
* there should be a hotkey to exit the popup (currently you need to click on the left, which means you need to move the mouse away from the filename you clicked on, so it's easy to lose track of which one you clicked)
* the syntax highlighting is kind of bad

**Comment by thuustalu** [comment]
- depending on the phase of the moon, sometimes you get extra line breaks when you copy-paste from the code area
- there should be a button that just copies the whole thing to clipboard

**Comment by thuustalu** [comment]
phase of the moon = Python and \r\n line endings, probably

**Comment by prandla** [comment]
implemented in 536448407de55e46f199d69fd32723304407127c and f51d1cac045eb9aaa0d671f67c9f7a916665a5d3
