### ISSUE TITLE
Notifications of participant questions

### ISSUE THREAD

**Issue by ahtotruu** [e-i-o/cms#9]
Consider adding the possibility of email/slack/etc notifications when a new question is posted by a contest participant. This is useful mostly for week-long take-home contests when jury members can't be expected to be monitoring the admin interface 'round the clock.

**Comment by prandla** [comment]
notes for matrix implementation: [theory](https://uhoreg.gitlab.io/matrix-tutorial/sending.html), [code sample](https://github.com/louislam/uptime-kuma/blob/bbc75b840bc0eefa1d7296a78487ad8ed4c8a97a/server/notification-providers/matrix.js#L40)
cms integration (how italy did their telegram notifier): https://github.com/cms-dev/cms/commit/3d0b71a20b458d33289a4293fcfe8caedf047b8b

**Comment by prandla** [comment]
implemented in 32f90fce305e0d553e73f510716d92c3997f10f1
